project:
  type: website

website:
  title: "Demo App Engine With Quarto"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: shinylive.qmd
        text: Shiny Live
      - about.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



